using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LisAeroGest.Migrations.Postgres
{
    public partial class InitialCreatePostgres : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
                    migrationBuilder.Sql(@"
        CREATE TABLE ""Aircrafts"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""Brand"" character varying(100) NOT NULL,
            ""Model"" character varying(100) NOT NULL,
            ""EconomySeats"" integer NOT NULL,
            ""BusinessSeats"" integer NOT NULL,
            ""ImageId"" uuid NOT NULL,
            ""IsAvailable"" boolean NOT NULL,
            ""WasDeleted"" boolean NOT NULL,
            CONSTRAINT ""PK_Aircrafts"" PRIMARY KEY (""Id"")
        );

        CREATE TABLE ""Airlines"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""Name"" character varying(100) NOT NULL,
            ""IATACode"" character varying(2) NOT NULL,
            ""Country"" character varying(100) NOT NULL,
            ""ImageId"" uuid NOT NULL,
            ""WasDeleted"" boolean NOT NULL,
            CONSTRAINT ""PK_Airlines"" PRIMARY KEY (""Id"")
        );

        CREATE TABLE ""Airports"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""Name"" character varying(100) NOT NULL,
            ""City"" character varying(100) NOT NULL,
            ""Country"" character varying(100) NOT NULL,
            ""IATACode"" character varying(3) NOT NULL,
            ""ImageId"" uuid NOT NULL,
            ""WasDeleted"" boolean NOT NULL,
            ""DefaultFee"" numeric(10,2) NOT NULL,
            CONSTRAINT ""PK_Airports"" PRIMARY KEY (""Id"")
        );

        CREATE TABLE ""AspNetRoles"" (
            ""Id"" character varying(450) NOT NULL,
            ""Name"" character varying(256) NULL,
            ""NormalizedName"" character varying(256) NULL,
            ""ConcurrencyStamp"" text NULL,
            CONSTRAINT ""PK_AspNetRoles"" PRIMARY KEY (""Id"")
        );

        CREATE TABLE ""AspNetUsers"" (
            ""Id"" character varying(450) NOT NULL,
            ""FirstName"" character varying(100) NOT NULL,
            ""LastName"" character varying(100) NOT NULL,
            ""Address"" character varying(200) NULL,
            ""ImageId"" uuid NOT NULL,
            ""IsPasswordSet"" boolean NOT NULL,
            ""UserName"" character varying(256) NULL,
            ""NormalizedUserName"" character varying(256) NULL,
            ""Email"" character varying(256) NULL,
            ""NormalizedEmail"" character varying(256) NULL,
            ""EmailConfirmed"" boolean NOT NULL,
            ""PasswordHash"" text NULL,
            ""SecurityStamp"" text NULL,
            ""ConcurrencyStamp"" text NULL,
            ""PhoneNumber"" text NULL,
            ""PhoneNumberConfirmed"" boolean NOT NULL,
            ""TwoFactorEnabled"" boolean NOT NULL,
            ""LockoutEnd"" timestamp with time zone NULL,
            ""LockoutEnabled"" boolean NOT NULL,
            ""AccessFailedCount"" integer NOT NULL,
            CONSTRAINT ""PK_AspNetUsers"" PRIMARY KEY (""Id"")
        );

        CREATE TABLE ""Gates"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""GateNumber"" character varying(10) NOT NULL,
            ""Terminal"" character varying(50) NOT NULL,
            ""Status"" text NOT NULL,
            ""WasDeleted"" boolean NOT NULL,
            CONSTRAINT ""PK_Gates"" PRIMARY KEY (""Id"")
        );

        CREATE TABLE ""AspNetRoleClaims"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""RoleId"" character varying(450) NOT NULL,
            ""ClaimType"" text NULL,
            ""ClaimValue"" text NULL,
            CONSTRAINT ""PK_AspNetRoleClaims"" PRIMARY KEY (""Id""),
            CONSTRAINT ""FK_AspNetRoleClaims_AspNetRoles_RoleId"" FOREIGN KEY (""RoleId"") REFERENCES ""AspNetRoles"" (""Id"") ON DELETE CASCADE
        );

        CREATE TABLE ""AspNetUserClaims"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""UserId"" character varying(450) NOT NULL,
            ""ClaimType"" text NULL,
            ""ClaimValue"" text NULL,
            CONSTRAINT ""PK_AspNetUserClaims"" PRIMARY KEY (""Id""),
            CONSTRAINT ""FK_AspNetUserClaims_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
        );

        CREATE TABLE ""AspNetUserLogins"" (
            ""LoginProvider"" character varying(450) NOT NULL,
            ""ProviderKey"" character varying(450) NOT NULL,
            ""ProviderDisplayName"" text NULL,
            ""UserId"" character varying(450) NOT NULL,
            CONSTRAINT ""PK_AspNetUserLogins"" PRIMARY KEY (""LoginProvider"", ""ProviderKey""),
            CONSTRAINT ""FK_AspNetUserLogins_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
        );

        CREATE TABLE ""AspNetUserRoles"" (
            ""UserId"" character varying(450) NOT NULL,
            ""RoleId"" character varying(450) NOT NULL,
            CONSTRAINT ""PK_AspNetUserRoles"" PRIMARY KEY (""UserId"", ""RoleId""),
            CONSTRAINT ""FK_AspNetUserRoles_AspNetRoles_RoleId"" FOREIGN KEY (""RoleId"") REFERENCES ""AspNetRoles"" (""Id"") ON DELETE CASCADE,
            CONSTRAINT ""FK_AspNetUserRoles_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
        );

        CREATE TABLE ""AspNetUserTokens"" (
            ""UserId"" character varying(450) NOT NULL,
            ""LoginProvider"" character varying(450) NOT NULL,
            ""Name"" character varying(450) NOT NULL,
            ""Value"" text NULL,
            CONSTRAINT ""PK_AspNetUserTokens"" PRIMARY KEY (""UserId"", ""LoginProvider"", ""Name""),
            CONSTRAINT ""FK_AspNetUserTokens_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
        );

        CREATE TABLE ""ForumTopics"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""Title"" character varying(200) NOT NULL,
            ""Content"" text NOT NULL,
            ""Category"" character varying(50) NULL,
            ""CreatedByUserId"" character varying(450) NULL,
            ""CreatedAt"" timestamp without time zone NOT NULL,
            ""IsClosed"" boolean NOT NULL,
            ""WasDeleted"" boolean NOT NULL,
            CONSTRAINT ""PK_ForumTopics"" PRIMARY KEY (""Id""),
            CONSTRAINT ""FK_ForumTopics_AspNetUsers_CreatedByUserId"" FOREIGN KEY (""CreatedByUserId"") REFERENCES ""AspNetUsers"" (""Id"")
        );

        CREATE TABLE ""Notifications"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""UserId"" character varying(450) NOT NULL,
            ""Title"" character varying(200) NOT NULL,
            ""Message"" character varying(500) NOT NULL,
            ""Link"" character varying(300) NULL,
            ""Icon"" character varying(50) NOT NULL,
            ""ColorClass"" character varying(30) NOT NULL,
            ""IsRead"" boolean NOT NULL,
            ""CreatedAt"" timestamp without time zone NOT NULL,
            ""Type"" character varying(50) NOT NULL,
            CONSTRAINT ""PK_Notifications"" PRIMARY KEY (""Id""),
            CONSTRAINT ""FK_Notifications_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
        );

        CREATE TABLE ""Passengers"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""FirstName"" character varying(100) NOT NULL,
            ""LastName"" character varying(100) NOT NULL,
            ""ImageId"" uuid NOT NULL,
            ""RegistrationDate"" timestamp without time zone NOT NULL,
            ""DocumentType"" text NOT NULL,
            ""DocumentNumber"" text NOT NULL,
            ""BirthDate"" timestamp without time zone NULL,
            ""UserId"" character varying(450) NULL,
            ""Email"" character varying(150) NOT NULL,
            ""WasDeleted"" boolean NOT NULL,
            CONSTRAINT ""PK_Passengers"" PRIMARY KEY (""Id""),
            CONSTRAINT ""FK_Passengers_AspNetUsers_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE
        );

        CREATE TABLE ""Flights"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""FlightNumber"" character varying(10) NOT NULL,
            ""AirlineId"" integer NOT NULL,
            ""OriginAirportId"" integer NOT NULL,
            ""DestinationAirportId"" integer NOT NULL,
            ""AircraftId"" integer NOT NULL,
            ""GateId"" integer NULL,
            ""DepartureTime"" timestamp without time zone NOT NULL,
            ""ArrivalTime"" timestamp without time zone NOT NULL,
            ""BasePrice"" numeric(18,2) NOT NULL,
            ""Status"" text NOT NULL,
            ""DelayedDepartureTime"" timestamp without time zone NULL,
            ""WasDeleted"" boolean NOT NULL,
            CONSTRAINT ""PK_Flights"" PRIMARY KEY (""Id""),
            CONSTRAINT ""FK_Flights_Aircrafts_AircraftId"" FOREIGN KEY (""AircraftId"") REFERENCES ""Aircrafts"" (""Id""),
            CONSTRAINT ""FK_Flights_Airlines_AirlineId"" FOREIGN KEY (""AirlineId"") REFERENCES ""Airlines"" (""Id""),
            CONSTRAINT ""FK_Flights_Airports_DestinationAirportId"" FOREIGN KEY (""DestinationAirportId"") REFERENCES ""Airports"" (""Id""),
            CONSTRAINT ""FK_Flights_Airports_OriginAirportId"" FOREIGN KEY (""OriginAirportId"") REFERENCES ""Airports"" (""Id""),
            CONSTRAINT ""FK_Flights_Gates_GateId"" FOREIGN KEY (""GateId"") REFERENCES ""Gates"" (""Id"")
        );

        CREATE TABLE ""ForumComments"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""Content"" text NOT NULL,
            ""ForumTopicId"" integer NOT NULL,
            ""CreatedByUserId"" character varying(450) NULL,
            ""CreatedAt"" timestamp without time zone NOT NULL,
            ""IsApproved"" boolean NOT NULL,
            ""WasDeleted"" boolean NOT NULL,
            CONSTRAINT ""PK_ForumComments"" PRIMARY KEY (""Id""),
            CONSTRAINT ""FK_ForumComments_AspNetUsers_CreatedByUserId"" FOREIGN KEY (""CreatedByUserId"") REFERENCES ""AspNetUsers"" (""Id""),
            CONSTRAINT ""FK_ForumComments_ForumTopics_ForumTopicId"" FOREIGN KEY (""ForumTopicId"") REFERENCES ""ForumTopics"" (""Id"") ON DELETE CASCADE
        );

        CREATE TABLE ""Seats"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""Code"" character varying(10) NOT NULL,
            ""SeatClass"" text NOT NULL,
            ""BasePrice"" numeric(18,2) NOT NULL,
            ""IsAvailable"" boolean NOT NULL,
            ""AircraftId"" integer NOT NULL,
            ""FlightId"" integer NULL,
            ""WasDeleted"" boolean NOT NULL,
            CONSTRAINT ""PK_Seats"" PRIMARY KEY (""Id""),
            CONSTRAINT ""FK_Seats_Aircrafts_AircraftId"" FOREIGN KEY (""AircraftId"") REFERENCES ""Aircrafts"" (""Id"") ON DELETE CASCADE,
            CONSTRAINT ""FK_Seats_Flights_FlightId"" FOREIGN KEY (""FlightId"") REFERENCES ""Flights"" (""Id"")
        );

        CREATE TABLE ""Tickets"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""PassengerId"" integer NOT NULL,
            ""FlightId"" integer NOT NULL,
            ""SeatId"" integer NOT NULL,
            ""TotalPrice"" numeric(18,2) NOT NULL,
            ""ExtraLuggage"" boolean NOT NULL,
            ""MealIncluded"" boolean NOT NULL,
            ""Status"" text NOT NULL,
            ""PurchaseDate"" timestamp without time zone NOT NULL,
            ""ReservationExpiresAt"" timestamp without time zone NULL,
            ""CheckInDate"" timestamp without time zone NULL,
            ""CreatedByUserId"" character varying(450) NULL,
            ""WasDeleted"" boolean NOT NULL,
            CONSTRAINT ""PK_Tickets"" PRIMARY KEY (""Id""),
            CONSTRAINT ""FK_Tickets_AspNetUsers_CreatedByUserId"" FOREIGN KEY (""CreatedByUserId"") REFERENCES ""AspNetUsers"" (""Id""),
            CONSTRAINT ""FK_Tickets_Flights_FlightId"" FOREIGN KEY (""FlightId"") REFERENCES ""Flights"" (""Id""),
            CONSTRAINT ""FK_Tickets_Passengers_PassengerId"" FOREIGN KEY (""PassengerId"") REFERENCES ""Passengers"" (""Id""),
            CONSTRAINT ""FK_Tickets_Seats_SeatId"" FOREIGN KEY (""SeatId"") REFERENCES ""Seats"" (""Id"")
        );

        CREATE TABLE ""BoardingPasses"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
            ""TicketId"" integer NOT NULL,
            ""SequenceNumber"" integer NOT NULL,
            ""Gate"" text NULL,
            ""IssuedAt"" timestamp without time zone NOT NULL,
            ""QRCode"" character varying(200) NOT NULL,
            CONSTRAINT ""PK_BoardingPasses"" PRIMARY KEY (""Id""),
            CONSTRAINT ""FK_BoardingPasses_Tickets_TicketId"" FOREIGN KEY (""TicketId"") REFERENCES ""Tickets"" (""Id"")
        );

        CREATE UNIQUE INDEX ""IX_Airlines_IATACode"" ON ""Airlines"" (""IATACode"") WHERE ""WasDeleted"" = false;
        CREATE UNIQUE INDEX ""IX_Airlines_Name"" ON ""Airlines"" (""Name"") WHERE ""WasDeleted"" = false;
        CREATE UNIQUE INDEX ""IX_Airports_IATACode"" ON ""Airports"" (""IATACode"") WHERE ""WasDeleted"" = false;
        CREATE UNIQUE INDEX ""IX_Airports_Name"" ON ""Airports"" (""Name"") WHERE ""WasDeleted"" = false;
        CREATE INDEX ""IX_AspNetRoleClaims_RoleId"" ON ""AspNetRoleClaims"" (""RoleId"");
        CREATE UNIQUE INDEX ""RoleNameIndex"" ON ""AspNetRoles"" (""NormalizedName"") WHERE ""NormalizedName"" IS NOT NULL;
        CREATE INDEX ""IX_AspNetUserClaims_UserId"" ON ""AspNetUserClaims"" (""UserId"");
        CREATE INDEX ""IX_AspNetUserLogins_UserId"" ON ""AspNetUserLogins"" (""UserId"");
        CREATE INDEX ""IX_AspNetUserRoles_RoleId"" ON ""AspNetUserRoles"" (""RoleId"");
        CREATE INDEX ""EmailIndex"" ON ""AspNetUsers"" (""NormalizedEmail"");
        CREATE UNIQUE INDEX ""UserNameIndex"" ON ""AspNetUsers"" (""NormalizedUserName"") WHERE ""NormalizedUserName"" IS NOT NULL;
        CREATE UNIQUE INDEX ""IX_BoardingPasses_TicketId"" ON ""BoardingPasses"" (""TicketId"");
        CREATE INDEX ""IX_Flights_AircraftId"" ON ""Flights"" (""AircraftId"");
        CREATE INDEX ""IX_Flights_AirlineId"" ON ""Flights"" (""AirlineId"");
        CREATE INDEX ""IX_Flights_DestinationAirportId"" ON ""Flights"" (""DestinationAirportId"");
        CREATE INDEX ""IX_Flights_GateId"" ON ""Flights"" (""GateId"");
        CREATE INDEX ""IX_Flights_OriginAirportId"" ON ""Flights"" (""OriginAirportId"");
        CREATE INDEX ""IX_ForumComments_CreatedByUserId"" ON ""ForumComments"" (""CreatedByUserId"");
        CREATE INDEX ""IX_ForumComments_ForumTopicId"" ON ""ForumComments"" (""ForumTopicId"");
        CREATE INDEX ""IX_ForumTopics_CreatedByUserId"" ON ""ForumTopics"" (""CreatedByUserId"");
        CREATE INDEX ""IX_Notifications_UserId"" ON ""Notifications"" (""UserId"");
        CREATE INDEX ""IX_Passengers_UserId"" ON ""Passengers"" (""UserId"");
        CREATE INDEX ""IX_Seats_AircraftId"" ON ""Seats"" (""AircraftId"");
        CREATE INDEX ""IX_Seats_FlightId"" ON ""Seats"" (""FlightId"");
        CREATE INDEX ""IX_Tickets_CreatedByUserId"" ON ""Tickets"" (""CreatedByUserId"");
        CREATE INDEX ""IX_Tickets_FlightId"" ON ""Tickets"" (""FlightId"");
        CREATE INDEX ""IX_Tickets_PassengerId"" ON ""Tickets"" (""PassengerId"");
        CREATE INDEX ""IX_Tickets_SeatId"" ON ""Tickets"" (""SeatId"");
        ");
                }

                protected override void Down(MigrationBuilder migrationBuilder)
                {
                    migrationBuilder.Sql(@"
        DROP TABLE IF EXISTS ""BoardingPasses"";
        DROP TABLE IF EXISTS ""Tickets"";
        DROP TABLE IF EXISTS ""Seats"";
        DROP TABLE IF EXISTS ""ForumComments"";
        DROP TABLE IF EXISTS ""Flights"";
        DROP TABLE IF EXISTS ""Passengers"";
        DROP TABLE IF EXISTS ""Notifications"";
        DROP TABLE IF EXISTS ""ForumTopics"";
        DROP TABLE IF EXISTS ""AspNetUserTokens"";
        DROP TABLE IF EXISTS ""AspNetUserRoles"";
        DROP TABLE IF EXISTS ""AspNetUserLogins"";
        DROP TABLE IF EXISTS ""AspNetUserClaims"";
        DROP TABLE IF EXISTS ""AspNetRoleClaims"";
        DROP TABLE IF EXISTS ""Gates"";
        DROP TABLE IF EXISTS ""AspNetUsers"";
        DROP TABLE IF EXISTS ""AspNetRoles"";
        DROP TABLE IF EXISTS ""Airports"";
        DROP TABLE IF EXISTS ""Airlines"";
        DROP TABLE IF EXISTS ""Aircrafts"";
        ");
        }
    }
}